# Generated by Django 5.1.6 on 2026-02-18 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('stationery', 'Stationery Shop'), ('duka_la_vinywaji', 'Duka la Vinywaji')], max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Shop',
                'verbose_name_plural': 'Shops',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(default=1, help_text='Shop/Store for this product', on_delete=django.db.models.deletion.CASCADE, to='tracker.shop'),
        ),
        migrations.AddField(
            model_name='stationeryitem',
            name='shop',
            field=models.ForeignKey(default=1, help_text='Shop/Store for this item', on_delete=django.db.models.deletion.CASCADE, to='tracker.shop'),
        ),
    ]
