# Generated by Django 5.1.6 on 2026-02-18 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_shop_product_shop_stationeryitem_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='shop',
            field=models.ForeignKey(default=1, help_text='Shop/Store for this sale', on_delete=django.db.models.deletion.CASCADE, to='tracker.shop'),
        ),
    ]
