# Generated by Django 5.1.6 on 2026-02-18 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_sale_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='shop',
            field=models.ForeignKey(default=1, help_text='Shop/Store for this customer', on_delete=django.db.models.deletion.CASCADE, to='tracker.shop'),
        ),
    ]
