# Generated by Django 5.1.6 on 2026-02-18 10:37

import django.db.models.deletion
from django.db import migrations, models


def fix_product_category_references(apps, schema_editor):
    """Fix Product.category references to point to ProductCategory instead of Category"""
    Product = apps.get_model('tracker', 'Product')
    Category = apps.get_model('tracker', 'Category')
    ProductCategory = apps.get_model('tracker', 'ProductCategory')
    Shop = apps.get_model('tracker', 'Shop')
    
    # Get the stationery shop (ID=1)
    stationery_shop = Shop.objects.get(id=1)
    
    # Migrate existing Categories to ProductCategories
    for category in Category.objects.all():
        # Create corresponding ProductCategory if it doesn't exist
        product_category, created = ProductCategory.objects.get_or_create(
            name=category.name,
            shop=stationery_shop,
            defaults={
                'description': category.description,
            }
        )
        
        # Update all products that reference this category
        Product.objects.filter(category_id=category.id).update(category_id=product_category.id)


def reverse_fix_product_category_references(apps, schema_editor):
    """Reverse the product category references fix"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0015_customer_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='tracker.shop'),
        ),
        migrations.AddField(
            model_name='debt',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='tracker.shop'),
        ),
        migrations.AddField(
            model_name='expenditure',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='expenditures', to='tracker.shop'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to='tracker.shop'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='tracker.shop'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='assigned_shops',
            field=models.ManyToManyField(blank=True, help_text='Shops this user can access', to='tracker.shop'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='default_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_users', to='tracker.shop'),
        ),
        migrations.RunPython(fix_product_category_references, reverse_fix_product_category_references),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='tracker.shop'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='tracker.productcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='tracker.shop'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(help_text='Stock Keeping Unit', max_length=50),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sale',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='tracker.shop'),
        ),
        migrations.AlterField(
            model_name='stationeryitem',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stationery_items', to='tracker.shop'),
        ),
        migrations.AlterField(
            model_name='stationeryitem',
            name='sku',
            field=models.CharField(help_text='Stock Keeping Unit', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'shop')},
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('sku', 'shop')},
        ),
        migrations.AlterUniqueTogether(
            name='productcategory',
            unique_together={('name', 'shop')},
        ),
        migrations.AlterUniqueTogether(
            name='stationeryitem',
            unique_together={('sku', 'shop')},
        ),
    ]
