# Generated by Django 5.1.6 on 2026-02-25 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_5_add_display_name_to_shop'),
        ('tracker', '0017_fix_debt_shop_assignments'),
    ]

    operations = [
    ]
