# Generated by Django 5.1.6 on 2026-03-11 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0018_merge_20260225_0820'),
    ]

    operations = [
    ]
