# Generated by Django 5.1.6 on 2026-03-11 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0020_assign_maji_to_duka_la_vinywaji'),
    ]

    operations = [
    ]
