# Generated by Django 4.2.7 on 2026-05-10 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0021_assign_maji_to_duka_la_vinywaji'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='User must be approved by admin before accessing the system'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='display_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shop',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='shop',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(choices=[('stationery', 'Stationery Shop'), ('duka_la_vinywaji', 'Duka la Vinywaji')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
