# Generated by Django 4.2.7 on 2026-05-10 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0022_userprofile_is_approved_alter_shop_address_and_more'),
    ]

    operations = [
    ]
